---
title: matrixBP
format: gfm
---


## Installation

To install the matrixBP package, you can use the following command in R:

```
devtools::install_github('IDSS-NIAID/matrixBP')
```

## Examples

```{r}
#| dpi: 300
library(matrixBP)
library(dplyr)
library(RColorBrewer)
library(cowplot)
theme_set(theme_cowplot())


# Load the data
data(metlip)

# colors for facet_grid labels
grp_colors <- levels(metlip$Group) |>
  length() |>
  brewer.pal('Set3')
names(grp_colors) <- levels(metlip$Group)


# plot with colored facets
matrix_barplot(metlip, aes(x = Lipid, y = neg_log_p, color = log2FC),
               cols = vars(Group), rows = vars(sample), facet_colors = grp_colors) |>
  mBP_legend()

# plot in portrait orientation
matrix_barplot(metlip, aes(x = neg_log_p, y = Lipid, color = log2FC),
               cols = vars(sample), rows = vars(Group), facet_colors = grp_colors,
               orientation = 'portrait') |>
  mBP_legend(legend.position = 'left')

# change the color of the bars
g1 <- matrix_barplot(metlip, aes(x = Lipid, y = neg_log_p, color = log2FC),
               cols = vars(Group), rows = vars(sample), facet_colors = grp_colors) +
  scale_color_gradient2(low = 'purple3', high = 'orange3')

mBP_legend(g1)


# plots with labeled facets
matrix_barplot(metlip, aes(x = Lipid, y = neg_log_p, color = log2FC),
               cols = vars(Acyl_1), rows = vars(sample)) |>
  mBP_col_labels()

matrix_barplot(metlip, aes(x = neg_log_p, y = Lipid, color = log2FC),
               cols = vars(sample), rows = vars(Group), facet_colors = grp_colors,
               orientation = 'portrait') |>
  mBP_row_labels()

(filter(metlip, Group %in% c('Lyso_PE', 'Lyso_PG', 'Lyso_PI')) |>
  matrix_barplot(aes(x = neg_log_p, y = Lipid, color = log2FC),
               cols = vars(sample), rows = vars(Group), facet_colors = grp_colors,
               orientation = 'portrait', 
               switch = TRUE, remove.y.labels = FALSE) +
      theme(legend.text = element_text(size = 6))) |>
  mBP_row_labels()


# plot with 12 samples
(g <- metlip |>
  bind_rows(mutate(metlip, sample = paste0(sample, 1)),
            mutate(metlip, sample = paste0(sample, 2))) |>
  
  matrix_barplot(aes(x = Lipid, y = neg_log_p, color = log2FC),
                 cols = vars(Group), rows = vars(sample), facet_colors = grp_colors) |>
  mBP_legend())


# larger plots seem to have trouble rendering in RStudio, but saving them as a file works
#ggsave('12_samples.png', g, width = 10, height = 10)
```

```{r}
#| eval: false
# trying to plot multiple samples on a single row causes the colors not to work
# if you get this error, that is the likely cause of the issue.
matrix_barplot(metlip, aes(x = Lipid, y = neg_log_p, color = log2FC),
               cols = vars(Group), facet_colors = grp_colors) |>
  mBP_legend()
```

    Error in matrix_barplot(metlip, aes(x = Lipid, y = neg_log_p, color = log2FC),  : 
       multiple rows or columns plotted to the same position. Did you forget to define `rows` or `cols`?
